import type { Metadata } from 'next';
import './globals.css';
import StoreProvider from './storeProvider';
import AppBar from '@/components/ui/appBar';
import { ThemeProvider } from './theme/ThemeProvider';
import { ThemeContextProvider } from './theme/ThemeContext';

export const metadata: Metadata = {
  title: `Tri's Next.js App`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body className='h-screen w-screen'>
        <ThemeContextProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <StoreProvider>
              <AppBar />
              <div className='prose absolute top-10 right-0 bottom-0 left-0 min-w-screen'>
                {children}
              </div>
            </StoreProvider>
          </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
